### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by top2001** [LilyPad/Bukkit-Connect#12]
Hello,

I was wondering what version of Bukkit-Connect to use at this is what happens on Spigot 1.8.3:

15.03 10:47:54 [Server] INFO Unable to start plugin - unsupported version?
15.03 10:47:54 [Server] WARN at java.lang.Thread.run(Thread.java:745)
15.03 10:47:54 [Server] WARN at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522)
15.03 10:47:54 [Server] WARN at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:200)
15.03 10:47:54 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.CraftServer.enablePlugins(CraftServer.java:316)
15.03 10:47:54 [Server] WARN at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugin(CraftServer.java:356)
15.03 10:47:54 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
15.03 10:47:54 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
15.03 10:47:54 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
15.03 10:47:54 [Server] WARN at lilypad.bukkit.connect.ConnectPlugin.onEnable(ConnectPlugin.java:44)
15.03 10:47:54 [Server] WARN at lilypad.bukkit.connect.injector.PacketInjector.injectStringMaxSize(PacketInjector.java:31)
15.03 10:47:54 [Server] WARN java.lang.NullPointerException
15.03 10:47:54 [Server] INFO Enabling LilyPad-Connect v86

**Comment by coelho** [comment]
v86 does not support 1.8.3. Use v88.
