### ISSUE TITLE
Add this fix to the next official release: Fix for incompatibility with my SpigotLib plugin.

### ISSUE THREAD

**Issue by gyurix** [LilyPad/Bukkit-Connect#17]
Hello,

A server owner, using my SpigotLib plugin have a compatibility issue, with this plugin. which I could fix. The fix is just a changing of one line:
I needed to change the 40. line in the lilypad.bukkit.connect.injector.NettyInjector class to:
ChannelHandler serverBootstrapAcceptor = channelPipeline.get("ServerBootstrap$ServerBootstrapAcceptor#0");
Please add this fix to the plugins official release too.

**Comment by coelho** [comment]
@gyurix Apologies for the incredibly late reply on this, is this still an issue?

**Comment by gyurix** [comment]
Wow it took almost a year to reply :)
By the way right now I am using BungeeCord, so actually if you have made the change I told then it should work.
