### ISSUE TITLE
1.11

### ISSUE THREAD

**Issue by dordsor21** [LilyPad/Bukkit-Connect#36]
Bukkit-Connect needs updating to 1.11 bukkit/spigot versions.

`[Connect] Unable to start plugin - unsupported version (v1_11_R1).`

**Comment by coelho** [comment]
Will be looking into this tomorrow. Should be a quick update.

**Comment by dordsor21** [comment]
Cheers!

**Comment by coelho** [comment]
@dordsor21 Would be absolutely fantastic if you could check if the latest version works for you on 1.11 :)

**Comment by dordsor21** [comment]
@coelho 
http://pastebin.com/raw/H8DAkPs5 on start-up latest spigot latest bukkit-connect

**Comment by dordsor21** [comment]
Seems you're trying to make a blank constructor 

`		if (!ConnectPlugin.getProtocol().getGeneralVersion().equalsIgnoreCase("1.9") && !ConnectPlugin.getProtocol().getGeneralVersion().equalsIgnoreCase("1.10")) {
			CtConstructor constructor = new CtConstructor(new CtClass[] { }, offlineMinecraftServerClass);
			constructor.setBody("{ super(null); }");
			offlineMinecraftServerClass.addConstructor(constructor);
		}`

in https://github.com/LilyPad/Bukkit-Connect/blob/master/src/main/java/lilypad/bukkit/connect/injector/OfflineInjector.java (71-75)
Perhaps add `&& !ConnectPlugin.getProtocol().getGeneralVersion().equalsIgnoreCase("1.11")` ?

**Comment by coelho** [comment]
I have no clue why that was hardcoded, but it's fixed in the latest commit. Try now? @dordsor21

**Comment by dordsor21** [comment]
Seems to load up perfectly, thanks @coelho !
