### ISSUE TITLE
NPE while getting API

### ISSUE THREAD

**Issue by manuelgu** [LilyPad/Bukkit-Connect#39]
Since upgrading to the latest version of GoLilypad and Bukkit-Connect I'm getting a NullPointerException here

```java
Connect connect = getServer().getServicesManager().getRegistration(Connect.class).getProvider();
```

**Comment by Joannou1** [comment]
Latest version fails to load on 1.12, that's probably why.
I made a working version for 1.12, but I'm not sure the changes I did to get it working would be the "right" way to do it.

**Comment by Joannou1** [comment]
https://github.com/LilyPad/JLilyPad/pull/8
and
https://github.com/dordsor21/Bukkit-Connect

should be enough to get you started on full 1.12 support

**Comment by coelho** [comment]
@Joannou1 

Can you please PR your Bukkit-Connect?

**Comment by Joannou1** [comment]
@coelho 

Sure, https://github.com/LilyPad/Bukkit-Connect/pull/40
Basically just copy pasted 11, seems to work well from my tests.

**Comment by coelho** [comment]
Merged.
