### ISSUE TITLE
Incompatibility with ProtocolSupport on 1.13+ and 1.12.2

### ISSUE THREAD

**Issue by Yive** [LilyPad/Bukkit-Connect#45]
Due to changes in ProtocolSupport, they've now completely removed isOnlineMode from the login handler causing players to be unable to log into 1.13.x servers. This will likely need to be completely rewritten https://github.com/LilyPad/Bukkit-Connect/blob/master/src/main/java/lilypad/bukkit/connect/login/LoginNettyInjectHandler.java#L175-L200

I tried to do it myself by using their API events, but couldn't figure out how to get the payload from the proxy so that it doesn't use offline mode UUIDs and properties.

ProtocolSupport build: 278

Stacktrace: https://i.tcpr.ca/I3TDJ6X When a player attempts to log in, this is what is outputted

Edit:

Appears to happen with the dev builds of ProtocolSupport that are before the 1.13 builds.

**Comment by dordsor21** [comment]
Bukkit-Connect doesn't actually support 1.13 yet anyway though

**Comment by Yive** [comment]
Just made this for when 1.13.x support is added, if ever

**Comment by Yive** [comment]
Closing because this will likely never be fixed
