### ISSUE TITLE
Bukkit-Connect incompatible with 1.15.2 due to getNettyInjectorChannelFutureList

### ISSUE THREAD

**Issue by FerusGrim** [LilyPad/Bukkit-Connect#52]
Between 1.15.1 and 1.15.2, `getNettyInjectorChannelFutureList` changed from `f` to `listeningChannels`. 

I've fixed this on my own servers, however, this update comes without a change to the package version (`v1_15_R1`), meaning I can't just PR it back into Bukkit-Connect without making it incompatible for 1.15 and 1.15.1.

**Comment by coelho** [comment]
Unfortunate that they did this. I think we should just adopt "listeningChannels" and if users want to use 1.15.1 (for some reason) they can just use the old version.

**Comment by FerusGrim** [comment]
I'll go ahead and make the PR, then.
